language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - "if [ $TRAVIS_RUST_VERSION = nightly ]; then cargo test --verbose; fi"
  - "if [ $TRAVIS_RUST_VERSION = nightly ]; then cargo bench --verbose; fi"
