[package]
name = "select"
version = "0.2.2"
authors = ["Utkarsh Kukreti <utkarshkukreti@gmail.com>"]
description = "A library to extract useful data from HTML documents, suitable for web scraping."
license = "MIT"
homepage = "https://github.com/utkarshkukreti/select.rs"
repository = "https://github.com/utkarshkukreti/select.rs"

[dev-dependencies]
speculate = "0.0.19"

[dependencies]
html5ever = "0.5.3"
bit-set = "0.4.0"
tendril = "0.2.2"
string_cache = "0.2.11"
