[package]
name = "select"
version = "0.1.0"
authors = ["Utkarsh Kukreti <utkarshkukreti@gmail.com>"]

[dev-dependencies]
speculate = "0.0.17"

[dependencies]
html5ever = "0.2.0"
html5ever_dom_sink = "0.2.0"
bit-set = "0.2.0"
