[package]
name = "select"
version = "0.2.0"
authors = ["Utkarsh Kukreti <utkarshkukreti@gmail.com>"]
description = "A library to extract useful data from HTML documents, suitable for web scraping."
license = "MIT"
homepage = "https://github.com/utkarshkukreti/select.rs"
repository = "https://github.com/utkarshkukreti/select.rs"

[dev-dependencies]
speculate = "0.0.17"

[dependencies]
html5ever = "0.2.6"
bit-set = "0.2.0"
tendril = "0.1.6"
string_cache = "0.2.0"
